name: Linux

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: linux-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "clang17"
            compiler: "clang-17"
            build: unit
            build_type: Release
            cxx_flags: "-std=c++20"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: raptor
          fetch-depth: 2
          submodules: true

      - name: Setup compiler
        uses: seqan/actions/setup-compiler@main
        with:
          compiler: ${{ matrix.compiler }}

      - name: Install OpenMP
        if: contains(matrix.name, 'clang')
        run: install libomp-17-dev

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.18.4

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake ../raptor/test/${{ matrix.build }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                                                   -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" \
                                                   -DRAPTOR_NATIVE_BUILD=OFF
          make -j2 gtest_build

      - name: Build tests
        continue-on-error: true
        id: build
        run: |
          cd build
          make VERBOSE=1 -j2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Run tests
        run: |
          cd build
          ctest . -j2 --output-on-failure

