name: CI on macOS

on:
  push:
    branches:
      - 'master'
  pull_request:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CMAKE_VERSION: 3.11.4
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-10.15
    timeout-minutes: 120
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "gcc11"
            cxx: "g++-11"
            cc: "gcc-11"
            build_type: Release

          - name: "gcc10"
            cxx: "g++-10"
            cc: "gcc-10"
            build_type: Release

          - name: "gcc9 (c++2a)"
            cxx: "g++-9"
            cc: "gcc-9"
            build_type: Release
            cxx_flags: "-std=c++2a"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: raptor
          fetch-depth: 2
          submodules: true

      - name: Configure Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install CMake
        run: bash ./raptor/lib/seqan3/.github/workflows/scripts/install_cmake.sh

      - name: Install ccache
        run: bash ./raptor/lib/seqan3/.github/workflows/scripts/install_via_brew.sh ccache

      - name: Install compiler ${{ matrix.cxx }}
        run: bash ./raptor/lib/seqan3/.github/workflows/scripts/install_via_brew.sh gcc $(echo "${{ matrix.cxx }}" | sed "s/g++-//g")

      - name: Load ccache
        uses: actions/cache@v2
        with:
          path: .ccache
          key: ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}-${{ github.run_number }}
          # Restoring: From current branch, otherwise from base branch, otherwise from any branch.
          restore-keys: |
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.base_ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir build
          cd build
          cmake ../raptor -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                          -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" \
                          -DRAPTOR_NATIVE_BUILD=OFF

      - name: Build tests
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 12
          CCACHE_MAXSIZE: 50M
        run: |
          ccache -z
          cd build
          make -k -j3 api_test cli_test
          ccache -sv

      - name: Run tests
        run: |
          cd build
          ctest . -j3 --output-on-failure
