# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Utility

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: util-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: false
      matrix:
        compiler: ["clang-18", "clang-17", "gcc-14", "gcc-13", "gcc-12", "intel"]
        include:
          - cxx_flags: "-Wno-interference-size"
          - compiler: "clang-18"
            cxx_flags: ""
          - compiler: "clang-17"
            cxx_flags: ""
          - compiler: "intel"
            cxx_flags: "-fp-model=strict -Wno-overriding-option"
    container:
      image: ghcr.io/seqan/${{ matrix.compiler }}
      volumes:
        - /home/runner:/home/runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake ../util/test -DCMAKE_BUILD_TYPE=Release \
                             -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}"

      - name: Build tests
        working-directory: build
        run: |
          ccache -z
          make -k
          ccache -svvx

